/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRelatoriosRouteImport } from './routes/_authenticated/relatorios'
import { Route as AuthenticatedReajustesRouteImport } from './routes/_authenticated/reajustes'
import { Route as AuthenticatedMultiContratoRouteImport } from './routes/_authenticated/multi-contrato'
import { Route as AuthenticatedItensRouteImport } from './routes/_authenticated/itens'
import { Route as AuthenticatedImportacaoRouteImport } from './routes/_authenticated/importacao'
import { Route as AuthenticatedFornecedorRouteImport } from './routes/_authenticated/fornecedor'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedContratosRouteImport } from './routes/_authenticated/contratos'
import { Route as AuthenticatedConfiguracoesRouteImport } from './routes/_authenticated/configuracoes'
import { Route as AuthenticatedComparadorRouteImport } from './routes/_authenticated/comparador'
import { Route as AuthenticatedCalculadoraRouteImport } from './routes/_authenticated/calculadora'
import { Route as AuthenticatedAnaliseFornecedoresRouteImport } from './routes/_authenticated/analise-fornecedores'
import { Route as AuthenticatedAnalisadorRouteImport } from './routes/_authenticated/analisador'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRelatoriosRoute = AuthenticatedRelatoriosRouteImport.update({
  id: '/relatorios',
  path: '/relatorios',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedReajustesRoute = AuthenticatedReajustesRouteImport.update({
  id: '/reajustes',
  path: '/reajustes',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMultiContratoRoute =
  AuthenticatedMultiContratoRouteImport.update({
    id: '/multi-contrato',
    path: '/multi-contrato',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedItensRoute = AuthenticatedItensRouteImport.update({
  id: '/itens',
  path: '/itens',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedImportacaoRoute = AuthenticatedImportacaoRouteImport.update({
  id: '/importacao',
  path: '/importacao',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFornecedorRoute = AuthenticatedFornecedorRouteImport.update({
  id: '/fornecedor',
  path: '/fornecedor',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedContratosRoute = AuthenticatedContratosRouteImport.update({
  id: '/contratos',
  path: '/contratos',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedConfiguracoesRoute =
  AuthenticatedConfiguracoesRouteImport.update({
    id: '/configuracoes',
    path: '/configuracoes',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedComparadorRoute = AuthenticatedComparadorRouteImport.update({
  id: '/comparador',
  path: '/comparador',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCalculadoraRoute =
  AuthenticatedCalculadoraRouteImport.update({
    id: '/calculadora',
    path: '/calculadora',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAnaliseFornecedoresRoute =
  AuthenticatedAnaliseFornecedoresRouteImport.update({
    id: '/analise-fornecedores',
    path: '/analise-fornecedores',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAnalisadorRoute = AuthenticatedAnalisadorRouteImport.update({
  id: '/analisador',
  path: '/analisador',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/analisador': typeof AuthenticatedAnalisadorRoute
  '/analise-fornecedores': typeof AuthenticatedAnaliseFornecedoresRoute
  '/calculadora': typeof AuthenticatedCalculadoraRoute
  '/comparador': typeof AuthenticatedComparadorRoute
  '/configuracoes': typeof AuthenticatedConfiguracoesRoute
  '/contratos': typeof AuthenticatedContratosRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/fornecedor': typeof AuthenticatedFornecedorRoute
  '/importacao': typeof AuthenticatedImportacaoRoute
  '/itens': typeof AuthenticatedItensRoute
  '/multi-contrato': typeof AuthenticatedMultiContratoRoute
  '/reajustes': typeof AuthenticatedReajustesRoute
  '/relatorios': typeof AuthenticatedRelatoriosRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/analisador': typeof AuthenticatedAnalisadorRoute
  '/analise-fornecedores': typeof AuthenticatedAnaliseFornecedoresRoute
  '/calculadora': typeof AuthenticatedCalculadoraRoute
  '/comparador': typeof AuthenticatedComparadorRoute
  '/configuracoes': typeof AuthenticatedConfiguracoesRoute
  '/contratos': typeof AuthenticatedContratosRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/fornecedor': typeof AuthenticatedFornecedorRoute
  '/importacao': typeof AuthenticatedImportacaoRoute
  '/itens': typeof AuthenticatedItensRoute
  '/multi-contrato': typeof AuthenticatedMultiContratoRoute
  '/reajustes': typeof AuthenticatedReajustesRoute
  '/relatorios': typeof AuthenticatedRelatoriosRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/analisador': typeof AuthenticatedAnalisadorRoute
  '/_authenticated/analise-fornecedores': typeof AuthenticatedAnaliseFornecedoresRoute
  '/_authenticated/calculadora': typeof AuthenticatedCalculadoraRoute
  '/_authenticated/comparador': typeof AuthenticatedComparadorRoute
  '/_authenticated/configuracoes': typeof AuthenticatedConfiguracoesRoute
  '/_authenticated/contratos': typeof AuthenticatedContratosRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/fornecedor': typeof AuthenticatedFornecedorRoute
  '/_authenticated/importacao': typeof AuthenticatedImportacaoRoute
  '/_authenticated/itens': typeof AuthenticatedItensRoute
  '/_authenticated/multi-contrato': typeof AuthenticatedMultiContratoRoute
  '/_authenticated/reajustes': typeof AuthenticatedReajustesRoute
  '/_authenticated/relatorios': typeof AuthenticatedRelatoriosRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/analisador'
    | '/analise-fornecedores'
    | '/calculadora'
    | '/comparador'
    | '/configuracoes'
    | '/contratos'
    | '/dashboard'
    | '/fornecedor'
    | '/importacao'
    | '/itens'
    | '/multi-contrato'
    | '/reajustes'
    | '/relatorios'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/analisador'
    | '/analise-fornecedores'
    | '/calculadora'
    | '/comparador'
    | '/configuracoes'
    | '/contratos'
    | '/dashboard'
    | '/fornecedor'
    | '/importacao'
    | '/itens'
    | '/multi-contrato'
    | '/reajustes'
    | '/relatorios'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/analisador'
    | '/_authenticated/analise-fornecedores'
    | '/_authenticated/calculadora'
    | '/_authenticated/comparador'
    | '/_authenticated/configuracoes'
    | '/_authenticated/contratos'
    | '/_authenticated/dashboard'
    | '/_authenticated/fornecedor'
    | '/_authenticated/importacao'
    | '/_authenticated/itens'
    | '/_authenticated/multi-contrato'
    | '/_authenticated/reajustes'
    | '/_authenticated/relatorios'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/relatorios': {
      id: '/_authenticated/relatorios'
      path: '/relatorios'
      fullPath: '/relatorios'
      preLoaderRoute: typeof AuthenticatedRelatoriosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/reajustes': {
      id: '/_authenticated/reajustes'
      path: '/reajustes'
      fullPath: '/reajustes'
      preLoaderRoute: typeof AuthenticatedReajustesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/multi-contrato': {
      id: '/_authenticated/multi-contrato'
      path: '/multi-contrato'
      fullPath: '/multi-contrato'
      preLoaderRoute: typeof AuthenticatedMultiContratoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/itens': {
      id: '/_authenticated/itens'
      path: '/itens'
      fullPath: '/itens'
      preLoaderRoute: typeof AuthenticatedItensRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/importacao': {
      id: '/_authenticated/importacao'
      path: '/importacao'
      fullPath: '/importacao'
      preLoaderRoute: typeof AuthenticatedImportacaoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/fornecedor': {
      id: '/_authenticated/fornecedor'
      path: '/fornecedor'
      fullPath: '/fornecedor'
      preLoaderRoute: typeof AuthenticatedFornecedorRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/contratos': {
      id: '/_authenticated/contratos'
      path: '/contratos'
      fullPath: '/contratos'
      preLoaderRoute: typeof AuthenticatedContratosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/configuracoes': {
      id: '/_authenticated/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof AuthenticatedConfiguracoesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/comparador': {
      id: '/_authenticated/comparador'
      path: '/comparador'
      fullPath: '/comparador'
      preLoaderRoute: typeof AuthenticatedComparadorRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/calculadora': {
      id: '/_authenticated/calculadora'
      path: '/calculadora'
      fullPath: '/calculadora'
      preLoaderRoute: typeof AuthenticatedCalculadoraRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/analise-fornecedores': {
      id: '/_authenticated/analise-fornecedores'
      path: '/analise-fornecedores'
      fullPath: '/analise-fornecedores'
      preLoaderRoute: typeof AuthenticatedAnaliseFornecedoresRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/analisador': {
      id: '/_authenticated/analisador'
      path: '/analisador'
      fullPath: '/analisador'
      preLoaderRoute: typeof AuthenticatedAnalisadorRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAnalisadorRoute: typeof AuthenticatedAnalisadorRoute
  AuthenticatedAnaliseFornecedoresRoute: typeof AuthenticatedAnaliseFornecedoresRoute
  AuthenticatedCalculadoraRoute: typeof AuthenticatedCalculadoraRoute
  AuthenticatedComparadorRoute: typeof AuthenticatedComparadorRoute
  AuthenticatedConfiguracoesRoute: typeof AuthenticatedConfiguracoesRoute
  AuthenticatedContratosRoute: typeof AuthenticatedContratosRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedFornecedorRoute: typeof AuthenticatedFornecedorRoute
  AuthenticatedImportacaoRoute: typeof AuthenticatedImportacaoRoute
  AuthenticatedItensRoute: typeof AuthenticatedItensRoute
  AuthenticatedMultiContratoRoute: typeof AuthenticatedMultiContratoRoute
  AuthenticatedReajustesRoute: typeof AuthenticatedReajustesRoute
  AuthenticatedRelatoriosRoute: typeof AuthenticatedRelatoriosRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAnalisadorRoute: AuthenticatedAnalisadorRoute,
  AuthenticatedAnaliseFornecedoresRoute: AuthenticatedAnaliseFornecedoresRoute,
  AuthenticatedCalculadoraRoute: AuthenticatedCalculadoraRoute,
  AuthenticatedComparadorRoute: AuthenticatedComparadorRoute,
  AuthenticatedConfiguracoesRoute: AuthenticatedConfiguracoesRoute,
  AuthenticatedContratosRoute: AuthenticatedContratosRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedFornecedorRoute: AuthenticatedFornecedorRoute,
  AuthenticatedImportacaoRoute: AuthenticatedImportacaoRoute,
  AuthenticatedItensRoute: AuthenticatedItensRoute,
  AuthenticatedMultiContratoRoute: AuthenticatedMultiContratoRoute,
  AuthenticatedReajustesRoute: AuthenticatedReajustesRoute,
  AuthenticatedRelatoriosRoute: AuthenticatedRelatoriosRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
